// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Y7CVy1p5OcysoiDPpxRAR61_3aig03s',
    appId: '1:757564809744:web:60b530c14ef5996b67e095',
    messagingSenderId: '757564809744',
    projectId: 'mywallet-e9b75',
    authDomain: 'mywallet-e9b75.firebaseapp.com',
    storageBucket: 'mywallet-e9b75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlvcKbFkeP_dDlLIdj2G2HOsZ21gXens0',
    appId: '1:757564809744:android:f14bd5a9ee4d619267e095',
    messagingSenderId: '757564809744',
    projectId: 'mywallet-e9b75',
    storageBucket: 'mywallet-e9b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRwaROlEpTirplGsDKjj22PRqrNMjrzY',
    appId: '1:757564809744:ios:4453532182f7baae67e095',
    messagingSenderId: '757564809744',
    projectId: 'mywallet-e9b75',
    storageBucket: 'mywallet-e9b75.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALRwaROlEpTirplGsDKjj22PRqrNMjrzY',
    appId: '1:757564809744:ios:4453532182f7baae67e095',
    messagingSenderId: '757564809744',
    projectId: 'mywallet-e9b75',
    storageBucket: 'mywallet-e9b75.firebasestorage.app',
    iosBundleId: 'com.example.mywallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Y7CVy1p5OcysoiDPpxRAR61_3aig03s',
    appId: '1:757564809744:web:c80e75f8cb64c47b67e095',
    messagingSenderId: '757564809744',
    projectId: 'mywallet-e9b75',
    authDomain: 'mywallet-e9b75.firebaseapp.com',
    storageBucket: 'mywallet-e9b75.firebasestorage.app',
  );
}
